
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mse
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubedata/mse"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mse
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mse
  labels:
    app: mse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mse
  template:
    metadata:
      labels:
        app: mse
    spec:
      volumes:
        - name: mse-storage
          persistentVolumeClaim:
            claimName: mse
      containers:
        - name: mse
          image: gdatacyberdefense/sampleexchange:1.0.0
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          ports:
            - containerPort: 8080
              name: mse-http
              protocol: TCP
          volumeMounts:
            - mountPath: "/mnt/sampleexportstorage/"
              name: mse-storage
        - name: mongodb
          image: mongo:4.0.20
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          volumeMounts:
            - mountPath: "/mnt/sampleexportstorage/"
              name: mse-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mse
  labels:
    name: mse
spec:
  type: NodePort
  selector:
    app: mse
  externalTrafficPolicy: Local
  ports:
    - name: mse-http
      port: 8080
      protocol: TCP
    