name: SampleExport

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Install dependencies
      run: dotnet restore SampleExchangeApi.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore SampleExchangeApi.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal SampleExchangeApi.sln

    # Run only if a tag with the format "*.*.*" is pushed.
    - name: Build docker image
      run: docker build -t gdatacyberdefense/sampleexchange:$RELEASE_VERSION .
      if: startsWith(github.ref, 'refs/tags')
    - name: Tag latest
      run: docker tag gdatacyberdefense/sampleexchange:$RELEASE_VERSION gdatacyberdefense/sampleexchange:latest
      if: startsWith(github.ref, 'refs/tags')
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }} 
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      if: startsWith(github.ref, 'refs/tags')
    - name: Push docker image
      run: docker push gdatacyberdefense/sampleexchange:$RELEASE_VERSION && docker push gdatacyberdefense/sampleexchange:latest
      if: startsWith(github.ref, 'refs/tags')
