name: .NET Core

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Install dependencies
      run: dotnet restore SampleExchangeApi.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore SampleExchangeApi.sln
    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal SampleExchangeApi.sln
    - name: Build docker image
      run: docker build -t sampleexchange:$RELEASE_VERSION .


    - name: Push docker image
      run: docker push sampleexchange:$RELEASE_VERSION
      if: env.RELEASE_VERSION == 'v[0-9]+.[0-9]+.[0-9]+*'
